webpackJsonp([2],{

/***/ 11:
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__vue_script__ = __webpack_require__(12)
	if (__vue_script__ &&
	    __vue_script__.__esModule &&
	    Object.keys(__vue_script__).length > 1) {
	  console.warn("[vue-loader] example-dev/src/views/tabs-page.vue: named exports in *.vue files are ignored.")}
	__vue_template__ = __webpack_require__(13)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) {
	(typeof module.exports === "function" ? (module.exports.options || (module.exports.options = {})) : module.exports).template = __vue_template__
	}
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
	  hotAPI.install(require("vue"), false)
	  if (!hotAPI.compatible) return
	  var id = "_v-012a645f/tabs-page.vue"
	  if (!module.hot.data) {
	    hotAPI.createRecord(id, module.exports)
	  } else {
	    hotAPI.update(id, module.exports, __vue_template__)
	  }
	})()}

/***/ },

/***/ 12:
/***/ function(module, exports) {

	"use strict";
	
	Object.defineProperty(exports, "__esModule", {
	  value: true
	});
	// <template>
	//   <section class="hy_c-module hy_t-grey">
	//    <div class="hy_o-wrapper">
	//      <h2 class="hy_c-headline hy_c-headline--h2 hy_t-grey">Tab System</h2>
	//      <hr class="hy_u-space-mb-2">
	//      <tabs class="c-price-lookup hy_o-layout__item  hy_u-size-3of3@sm hy_u-size-3of4@md hy_u-size-4of12@lg">
	//        <tab label="In a bundle">
	//          <p>
	//            <span>Save $5 per month</span> on Internet when bundled with TV, Home Phone or Mobility.
	//          </p>
	//          <div class="price1">
	//            <div class="regular-price">
	//              <p class="price"><span class="dollar">$</span>83</p>
	//              <span class="monthly">per month
	//              </span>
	//            </div>
	//          </div>
	//          <div class="price2">
	//            <div class="promo-price">
	//              <p class="newCustomers">New Internet customers</p>
	//              <p class="price"><span class="dollar">$</span>40</p>
	//              <p><span class="monthly">per month</span> <span class="break">for 3 months
	//            </div>
	//          </div>
	//          <button type="button" name="button" class="hy_c-button hy_c-button--flat hy_t-green">Order now</button>
	//        </tab>
	//        <tab label="Internet only">
	//          <p>
	//            <span>Save $5 per month</span> on Internet when bundled with TV, Home Phone or Mobility.
	//          </p>
	//          <div class="price1">
	//            <div class="regular-price">
	//              <p class="price"><span class="dollar">$</span>88</p>
	//              <span class="monthly">per month
	//              </span>
	//            </div>
	//          </div>
	//          <div class="price2">
	//            <div class="promo-price">
	//              <p class="newCustomers">New Internet customers</p>
	//              <p class="price"><span class="dollar">$</span>45</p>
	//              <p><span class="monthly">per month</span> <span class="break">for 3 months
	//              </span></p>
	//            </div>
	//          </div>
	//          <button type="button" name="button" class="hy_c-button hy_c-button--flat hy_t-green">Order now</button>
	//        </tab>
	//      </tabs>
	//    </div>
	//  </section>
	// </template>
	//
	// <script>
	
	exports.default = {};
	// </script>

	/* generated by vue-loader */

/***/ },

/***/ 13:
/***/ function(module, exports) {

	module.exports = "\n <section class=\"hy_c-module hy_t-grey\">\n  <div class=\"hy_o-wrapper\">\n    <h2 class=\"hy_c-headline hy_c-headline--h2 hy_t-grey\">Tab System</h2>\n    <hr class=\"hy_u-space-mb-2\">\n    <tabs class=\"c-price-lookup hy_o-layout__item  hy_u-size-3of3@sm hy_u-size-3of4@md hy_u-size-4of12@lg\">\n      <tab label=\"In a bundle\">\n        <p>\n          <span>Save $5 per month</span> on Internet when bundled with TV, Home Phone or Mobility.\n        </p>\n        <div class=\"price1\">\n          <div class=\"regular-price\">\n            <p class=\"price\"><span class=\"dollar\">$</span>83</p>\n            <span class=\"monthly\">per month\n            </span>\n          </div>\n        </div>\n        <div class=\"price2\">\n          <div class=\"promo-price\">\n            <p class=\"newCustomers\">New Internet customers</p>\n            <p class=\"price\"><span class=\"dollar\">$</span>40</p>\n            <p><span class=\"monthly\">per month</span> <span class=\"break\">for 3 months\n          </div>\n        </div>\n        <button type=\"button\" name=\"button\" class=\"hy_c-button hy_c-button--flat hy_t-green\">Order now</button>\n      </tab>\n      <tab label=\"Internet only\">\n        <p>\n          <span>Save $5 per month</span> on Internet when bundled with TV, Home Phone or Mobility.\n        </p>\n        <div class=\"price1\">\n          <div class=\"regular-price\">\n            <p class=\"price\"><span class=\"dollar\">$</span>88</p>\n            <span class=\"monthly\">per month\n            </span>\n          </div>\n        </div>\n        <div class=\"price2\">\n          <div class=\"promo-price\">\n            <p class=\"newCustomers\">New Internet customers</p>\n            <p class=\"price\"><span class=\"dollar\">$</span>45</p>\n            <p><span class=\"monthly\">per month</span> <span class=\"break\">for 3 months\n            </span></p>\n          </div>\n        </div>\n        <button type=\"button\" name=\"button\" class=\"hy_c-button hy_c-button--flat hy_t-green\">Order now</button>\n      </tab>\n    </tabs>\n  </div>\n</section>\n";

/***/ }

});
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9leGFtcGxlLWRldi9zcmMvdmlld3MvdGFicy1wYWdlLnZ1ZSIsIndlYnBhY2s6Ly8vdGFicy1wYWdlLnZ1ZSIsIndlYnBhY2s6Ly8vLi9leGFtcGxlLWRldi9zcmMvdmlld3MvdGFicy1wYWdlLnZ1ZT9kNTA4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxnR0FBK0Y7QUFDL0Y7QUFDQSxhQUFpQixjQUFjO0FBQy9CO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLElBQUc7QUFDSDtBQUNBO0FBQ0EsRUFBQyxJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUJDaUNEOzs7Ozs7Ozs7O0FDdkRBLG1sRSIsImZpbGUiOiIyLmFwcC5qcyIsInNvdXJjZXNDb250ZW50IjpbInZhciBfX3Z1ZV9zY3JpcHRfXywgX192dWVfdGVtcGxhdGVfX1xuX192dWVfc2NyaXB0X18gPSByZXF1aXJlKFwiISFiYWJlbCEuLy4uLy4uLy4uL25vZGVfbW9kdWxlcy92dWUtbG9hZGVyL2xpYi9zZWxlY3Rvci5qcz90eXBlPXNjcmlwdCZpbmRleD0wIS4vdGFicy1wYWdlLnZ1ZVwiKVxuaWYgKF9fdnVlX3NjcmlwdF9fICYmXG4gICAgX192dWVfc2NyaXB0X18uX19lc01vZHVsZSAmJlxuICAgIE9iamVjdC5rZXlzKF9fdnVlX3NjcmlwdF9fKS5sZW5ndGggPiAxKSB7XG4gIGNvbnNvbGUud2FybihcIlt2dWUtbG9hZGVyXSBleGFtcGxlLWRldi9zcmMvdmlld3MvdGFicy1wYWdlLnZ1ZTogbmFtZWQgZXhwb3J0cyBpbiAqLnZ1ZSBmaWxlcyBhcmUgaWdub3JlZC5cIil9XG5fX3Z1ZV90ZW1wbGF0ZV9fID0gcmVxdWlyZShcIiEhdnVlLWh0bWw/cmVtb3ZlUmVkdW5kYW50QXR0cmlidXRlcz1mYWxzZSEuLy4uLy4uLy4uL25vZGVfbW9kdWxlcy92dWUtbG9hZGVyL2xpYi9zZWxlY3Rvci5qcz90eXBlPXRlbXBsYXRlJmluZGV4PTAhLi90YWJzLXBhZ2UudnVlXCIpXG5tb2R1bGUuZXhwb3J0cyA9IF9fdnVlX3NjcmlwdF9fIHx8IHt9XG5pZiAobW9kdWxlLmV4cG9ydHMuX19lc01vZHVsZSkgbW9kdWxlLmV4cG9ydHMgPSBtb2R1bGUuZXhwb3J0cy5kZWZhdWx0XG5pZiAoX192dWVfdGVtcGxhdGVfXykge1xuKHR5cGVvZiBtb2R1bGUuZXhwb3J0cyA9PT0gXCJmdW5jdGlvblwiID8gKG1vZHVsZS5leHBvcnRzLm9wdGlvbnMgfHwgKG1vZHVsZS5leHBvcnRzLm9wdGlvbnMgPSB7fSkpIDogbW9kdWxlLmV4cG9ydHMpLnRlbXBsYXRlID0gX192dWVfdGVtcGxhdGVfX1xufVxuaWYgKG1vZHVsZS5ob3QpIHsoZnVuY3Rpb24gKCkgeyAgbW9kdWxlLmhvdC5hY2NlcHQoKVxuICB2YXIgaG90QVBJID0gcmVxdWlyZShcInZ1ZS1ob3QtcmVsb2FkLWFwaVwiKVxuICBob3RBUEkuaW5zdGFsbChyZXF1aXJlKFwidnVlXCIpLCBmYWxzZSlcbiAgaWYgKCFob3RBUEkuY29tcGF0aWJsZSkgcmV0dXJuXG4gIHZhciBpZCA9IFwiX3YtMDEyYTY0NWYvdGFicy1wYWdlLnZ1ZVwiXG4gIGlmICghbW9kdWxlLmhvdC5kYXRhKSB7XG4gICAgaG90QVBJLmNyZWF0ZVJlY29yZChpZCwgbW9kdWxlLmV4cG9ydHMpXG4gIH0gZWxzZSB7XG4gICAgaG90QVBJLnVwZGF0ZShpZCwgbW9kdWxlLmV4cG9ydHMsIF9fdnVlX3RlbXBsYXRlX18pXG4gIH1cbn0pKCl9XG5cblxuLyoqKioqKioqKioqKioqKioqXG4gKiogV0VCUEFDSyBGT09URVJcbiAqKiAuL2V4YW1wbGUtZGV2L3NyYy92aWV3cy90YWJzLXBhZ2UudnVlXG4gKiogbW9kdWxlIGlkID0gMTFcbiAqKiBtb2R1bGUgY2h1bmtzID0gMlxuICoqLyIsIjx0ZW1wbGF0ZT5cbiAgPHNlY3Rpb24gY2xhc3M9XCJoeV9jLW1vZHVsZSBoeV90LWdyZXlcIj5cbiAgIDxkaXYgY2xhc3M9XCJoeV9vLXdyYXBwZXJcIj5cbiAgICAgPGgyIGNsYXNzPVwiaHlfYy1oZWFkbGluZSBoeV9jLWhlYWRsaW5lLS1oMiBoeV90LWdyZXlcIj5UYWIgU3lzdGVtPC9oMj5cbiAgICAgPGhyIGNsYXNzPVwiaHlfdS1zcGFjZS1tYi0yXCI+XG4gICAgIDx0YWJzIGNsYXNzPVwiYy1wcmljZS1sb29rdXAgaHlfby1sYXlvdXRfX2l0ZW0gIGh5X3Utc2l6ZS0zb2YzQHNtIGh5X3Utc2l6ZS0zb2Y0QG1kIGh5X3Utc2l6ZS00b2YxMkBsZ1wiPlxuICAgICAgIDx0YWIgbGFiZWw9XCJJbiBhIGJ1bmRsZVwiPlxuICAgICAgICAgPHA+XG4gICAgICAgICAgIDxzcGFuPlNhdmUgJDUgcGVyIG1vbnRoPC9zcGFuPiBvbiBJbnRlcm5ldCB3aGVuIGJ1bmRsZWQgd2l0aCBUViwgSG9tZSBQaG9uZSBvciBNb2JpbGl0eS5cbiAgICAgICAgIDwvcD5cbiAgICAgICAgIDxkaXYgY2xhc3M9XCJwcmljZTFcIj5cbiAgICAgICAgICAgPGRpdiBjbGFzcz1cInJlZ3VsYXItcHJpY2VcIj5cbiAgICAgICAgICAgICA8cCBjbGFzcz1cInByaWNlXCI+PHNwYW4gY2xhc3M9XCJkb2xsYXJcIj4kPC9zcGFuPjgzPC9wPlxuICAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwibW9udGhseVwiPnBlciBtb250aFxuICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICA8L2Rpdj5cbiAgICAgICAgIDxkaXYgY2xhc3M9XCJwcmljZTJcIj5cbiAgICAgICAgICAgPGRpdiBjbGFzcz1cInByb21vLXByaWNlXCI+XG4gICAgICAgICAgICAgPHAgY2xhc3M9XCJuZXdDdXN0b21lcnNcIj5OZXcgSW50ZXJuZXQgY3VzdG9tZXJzPC9wPlxuICAgICAgICAgICAgIDxwIGNsYXNzPVwicHJpY2VcIj48c3BhbiBjbGFzcz1cImRvbGxhclwiPiQ8L3NwYW4+NDA8L3A+XG4gICAgICAgICAgICAgPHA+PHNwYW4gY2xhc3M9XCJtb250aGx5XCI+cGVyIG1vbnRoPC9zcGFuPiA8c3BhbiBjbGFzcz1cImJyZWFrXCI+Zm9yIDMgbW9udGhzXG4gICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgPC9kaXY+XG4gICAgICAgICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBuYW1lPVwiYnV0dG9uXCIgY2xhc3M9XCJoeV9jLWJ1dHRvbiBoeV9jLWJ1dHRvbi0tZmxhdCBoeV90LWdyZWVuXCI+T3JkZXIgbm93PC9idXR0b24+XG4gICAgICAgPC90YWI+XG4gICAgICAgPHRhYiBsYWJlbD1cIkludGVybmV0IG9ubHlcIj5cbiAgICAgICAgIDxwPlxuICAgICAgICAgICA8c3Bhbj5TYXZlICQ1IHBlciBtb250aDwvc3Bhbj4gb24gSW50ZXJuZXQgd2hlbiBidW5kbGVkIHdpdGggVFYsIEhvbWUgUGhvbmUgb3IgTW9iaWxpdHkuXG4gICAgICAgICA8L3A+XG4gICAgICAgICA8ZGl2IGNsYXNzPVwicHJpY2UxXCI+XG4gICAgICAgICAgIDxkaXYgY2xhc3M9XCJyZWd1bGFyLXByaWNlXCI+XG4gICAgICAgICAgICAgPHAgY2xhc3M9XCJwcmljZVwiPjxzcGFuIGNsYXNzPVwiZG9sbGFyXCI+JDwvc3Bhbj44ODwvcD5cbiAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cIm1vbnRobHlcIj5wZXIgbW9udGhcbiAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgPC9kaXY+XG4gICAgICAgICA8ZGl2IGNsYXNzPVwicHJpY2UyXCI+XG4gICAgICAgICAgIDxkaXYgY2xhc3M9XCJwcm9tby1wcmljZVwiPlxuICAgICAgICAgICAgIDxwIGNsYXNzPVwibmV3Q3VzdG9tZXJzXCI+TmV3IEludGVybmV0IGN1c3RvbWVyczwvcD5cbiAgICAgICAgICAgICA8cCBjbGFzcz1cInByaWNlXCI+PHNwYW4gY2xhc3M9XCJkb2xsYXJcIj4kPC9zcGFuPjQ1PC9wPlxuICAgICAgICAgICAgIDxwPjxzcGFuIGNsYXNzPVwibW9udGhseVwiPnBlciBtb250aDwvc3Bhbj4gPHNwYW4gY2xhc3M9XCJicmVha1wiPmZvciAzIG1vbnRoc1xuICAgICAgICAgICAgIDwvc3Bhbj48L3A+XG4gICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgPC9kaXY+XG4gICAgICAgICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBuYW1lPVwiYnV0dG9uXCIgY2xhc3M9XCJoeV9jLWJ1dHRvbiBoeV9jLWJ1dHRvbi0tZmxhdCBoeV90LWdyZWVuXCI+T3JkZXIgbm93PC9idXR0b24+XG4gICAgICAgPC90YWI+XG4gICAgIDwvdGFicz5cbiAgIDwvZGl2PlxuIDwvc2VjdGlvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQ+XG5cbmV4cG9ydCBkZWZhdWx0IHtcbn07XG48L3NjcmlwdD5cblxuXG5cbi8qKiBXRUJQQUNLIEZPT1RFUiAqKlxuICoqIHRhYnMtcGFnZS52dWU/ODY4MjlmYzBcbiAqKi8iLCJtb2R1bGUuZXhwb3J0cyA9IFwiXFxuIDxzZWN0aW9uIGNsYXNzPVxcXCJoeV9jLW1vZHVsZSBoeV90LWdyZXlcXFwiPlxcbiAgPGRpdiBjbGFzcz1cXFwiaHlfby13cmFwcGVyXFxcIj5cXG4gICAgPGgyIGNsYXNzPVxcXCJoeV9jLWhlYWRsaW5lIGh5X2MtaGVhZGxpbmUtLWgyIGh5X3QtZ3JleVxcXCI+VGFiIFN5c3RlbTwvaDI+XFxuICAgIDxociBjbGFzcz1cXFwiaHlfdS1zcGFjZS1tYi0yXFxcIj5cXG4gICAgPHRhYnMgY2xhc3M9XFxcImMtcHJpY2UtbG9va3VwIGh5X28tbGF5b3V0X19pdGVtICBoeV91LXNpemUtM29mM0BzbSBoeV91LXNpemUtM29mNEBtZCBoeV91LXNpemUtNG9mMTJAbGdcXFwiPlxcbiAgICAgIDx0YWIgbGFiZWw9XFxcIkluIGEgYnVuZGxlXFxcIj5cXG4gICAgICAgIDxwPlxcbiAgICAgICAgICA8c3Bhbj5TYXZlICQ1IHBlciBtb250aDwvc3Bhbj4gb24gSW50ZXJuZXQgd2hlbiBidW5kbGVkIHdpdGggVFYsIEhvbWUgUGhvbmUgb3IgTW9iaWxpdHkuXFxuICAgICAgICA8L3A+XFxuICAgICAgICA8ZGl2IGNsYXNzPVxcXCJwcmljZTFcXFwiPlxcbiAgICAgICAgICA8ZGl2IGNsYXNzPVxcXCJyZWd1bGFyLXByaWNlXFxcIj5cXG4gICAgICAgICAgICA8cCBjbGFzcz1cXFwicHJpY2VcXFwiPjxzcGFuIGNsYXNzPVxcXCJkb2xsYXJcXFwiPiQ8L3NwYW4+ODM8L3A+XFxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XFxcIm1vbnRobHlcXFwiPnBlciBtb250aFxcbiAgICAgICAgICAgIDwvc3Bhbj5cXG4gICAgICAgICAgPC9kaXY+XFxuICAgICAgICA8L2Rpdj5cXG4gICAgICAgIDxkaXYgY2xhc3M9XFxcInByaWNlMlxcXCI+XFxuICAgICAgICAgIDxkaXYgY2xhc3M9XFxcInByb21vLXByaWNlXFxcIj5cXG4gICAgICAgICAgICA8cCBjbGFzcz1cXFwibmV3Q3VzdG9tZXJzXFxcIj5OZXcgSW50ZXJuZXQgY3VzdG9tZXJzPC9wPlxcbiAgICAgICAgICAgIDxwIGNsYXNzPVxcXCJwcmljZVxcXCI+PHNwYW4gY2xhc3M9XFxcImRvbGxhclxcXCI+JDwvc3Bhbj40MDwvcD5cXG4gICAgICAgICAgICA8cD48c3BhbiBjbGFzcz1cXFwibW9udGhseVxcXCI+cGVyIG1vbnRoPC9zcGFuPiA8c3BhbiBjbGFzcz1cXFwiYnJlYWtcXFwiPmZvciAzIG1vbnRoc1xcbiAgICAgICAgICA8L2Rpdj5cXG4gICAgICAgIDwvZGl2PlxcbiAgICAgICAgPGJ1dHRvbiB0eXBlPVxcXCJidXR0b25cXFwiIG5hbWU9XFxcImJ1dHRvblxcXCIgY2xhc3M9XFxcImh5X2MtYnV0dG9uIGh5X2MtYnV0dG9uLS1mbGF0IGh5X3QtZ3JlZW5cXFwiPk9yZGVyIG5vdzwvYnV0dG9uPlxcbiAgICAgIDwvdGFiPlxcbiAgICAgIDx0YWIgbGFiZWw9XFxcIkludGVybmV0IG9ubHlcXFwiPlxcbiAgICAgICAgPHA+XFxuICAgICAgICAgIDxzcGFuPlNhdmUgJDUgcGVyIG1vbnRoPC9zcGFuPiBvbiBJbnRlcm5ldCB3aGVuIGJ1bmRsZWQgd2l0aCBUViwgSG9tZSBQaG9uZSBvciBNb2JpbGl0eS5cXG4gICAgICAgIDwvcD5cXG4gICAgICAgIDxkaXYgY2xhc3M9XFxcInByaWNlMVxcXCI+XFxuICAgICAgICAgIDxkaXYgY2xhc3M9XFxcInJlZ3VsYXItcHJpY2VcXFwiPlxcbiAgICAgICAgICAgIDxwIGNsYXNzPVxcXCJwcmljZVxcXCI+PHNwYW4gY2xhc3M9XFxcImRvbGxhclxcXCI+JDwvc3Bhbj44ODwvcD5cXG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cXFwibW9udGhseVxcXCI+cGVyIG1vbnRoXFxuICAgICAgICAgICAgPC9zcGFuPlxcbiAgICAgICAgICA8L2Rpdj5cXG4gICAgICAgIDwvZGl2PlxcbiAgICAgICAgPGRpdiBjbGFzcz1cXFwicHJpY2UyXFxcIj5cXG4gICAgICAgICAgPGRpdiBjbGFzcz1cXFwicHJvbW8tcHJpY2VcXFwiPlxcbiAgICAgICAgICAgIDxwIGNsYXNzPVxcXCJuZXdDdXN0b21lcnNcXFwiPk5ldyBJbnRlcm5ldCBjdXN0b21lcnM8L3A+XFxuICAgICAgICAgICAgPHAgY2xhc3M9XFxcInByaWNlXFxcIj48c3BhbiBjbGFzcz1cXFwiZG9sbGFyXFxcIj4kPC9zcGFuPjQ1PC9wPlxcbiAgICAgICAgICAgIDxwPjxzcGFuIGNsYXNzPVxcXCJtb250aGx5XFxcIj5wZXIgbW9udGg8L3NwYW4+IDxzcGFuIGNsYXNzPVxcXCJicmVha1xcXCI+Zm9yIDMgbW9udGhzXFxuICAgICAgICAgICAgPC9zcGFuPjwvcD5cXG4gICAgICAgICAgPC9kaXY+XFxuICAgICAgICA8L2Rpdj5cXG4gICAgICAgIDxidXR0b24gdHlwZT1cXFwiYnV0dG9uXFxcIiBuYW1lPVxcXCJidXR0b25cXFwiIGNsYXNzPVxcXCJoeV9jLWJ1dHRvbiBoeV9jLWJ1dHRvbi0tZmxhdCBoeV90LWdyZWVuXFxcIj5PcmRlciBub3c8L2J1dHRvbj5cXG4gICAgICA8L3RhYj5cXG4gICAgPC90YWJzPlxcbiAgPC9kaXY+XFxuPC9zZWN0aW9uPlxcblwiO1xuXG5cbi8qKioqKioqKioqKioqKioqKlxuICoqIFdFQlBBQ0sgRk9PVEVSXG4gKiogLi9+L3Z1ZS1odG1sLWxvYWRlcj9yZW1vdmVSZWR1bmRhbnRBdHRyaWJ1dGVzPWZhbHNlIS4vfi92dWUtbG9hZGVyL2xpYi9zZWxlY3Rvci5qcz90eXBlPXRlbXBsYXRlJmluZGV4PTAhLi9leGFtcGxlLWRldi9zcmMvdmlld3MvdGFicy1wYWdlLnZ1ZVxuICoqIG1vZHVsZSBpZCA9IDEzXG4gKiogbW9kdWxlIGNodW5rcyA9IDJcbiAqKi8iXSwic291cmNlUm9vdCI6IiJ9