webpackJsonp([3],{

/***/ 14:
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__vue_script__ = __webpack_require__(15)
	if (__vue_script__ &&
	    __vue_script__.__esModule &&
	    Object.keys(__vue_script__).length > 1) {
	  console.warn("[vue-loader] example-dev/src/views/legal-page.vue: named exports in *.vue files are ignored.")}
	__vue_template__ = __webpack_require__(16)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) {
	(typeof module.exports === "function" ? (module.exports.options || (module.exports.options = {})) : module.exports).template = __vue_template__
	}
	if (false) {(function () {  module.hot.accept()
	  var hotAPI = require("vue-hot-reload-api")
	  hotAPI.install(require("vue"), false)
	  if (!hotAPI.compatible) return
	  var id = "_v-a62ca3dc/legal-page.vue"
	  if (!module.hot.data) {
	    hotAPI.createRecord(id, module.exports)
	  } else {
	    hotAPI.update(id, module.exports, __vue_template__)
	  }
	})()}

/***/ },

/***/ 15:
/***/ function(module, exports) {

	"use strict";
	
	Object.defineProperty(exports, "__esModule", {
	  value: true
	});
	// <template>
	//   <section class="hy_c-module hy_t-grey">
	//    <div class="hy_o-wrapper">
	//      <h2 class="hy_c-headline hy_c-headline--h2 hy_t-grey">Legal System</h2>
	//      <hr class="hy_u-space-mb-2">
	//      <p class="hy_c-copy hy_c-copy--body hy_t-grey">
	//        Lorem ipsum<legal-counter
	//          v-overlay-opener="legal-overlay"
	//          legal-key="hs-referral-terms"
	//          legal-lang="en" legal-region="bc"
	//          ></legal-counter> dolor sit amet, consectetur adipiscing elit,
	//        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	//        <legal-counter
	//          v-overlay-opener="legal-overlay"
	//          legal-key="1-year-offer-stim"
	//          legal-lang="en" legal-region="bc"
	//          ></legal-counter>
	//        Ut enim ad<legal-counter
	//          v-overlay-opener="legal-overlay"
	//          legal-key="fibre-promotions-ffg"
	//          legal-lang="en" legal-region="bc"
	//          ></legal-counter>  minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
	//        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu <legal-counter
	//          v-overlay-opener="legal-overlay"
	//          legal-key="fibre-free-installation"
	//          legal-lang="en" legal-region="bc"
	//          ></legal-counter>fugiat nulla pariatur.
	//        Excepteur<legal-counter
	//          v-overlay-opener="legal-overlay"
	//          legal-key="fibre-promotions-ffg"
	//          legal-lang="en" legal-region="bc"
	//          ></legal-counter> sint occaecat cupidatat non proident,
	//        sunt in culpa qui officia deserunt mollit <legal-counter
	//          v-overlay-opener="legal-overlay"
	//          legal-key="fibre-telus-and-network-logos"
	//          legal-lang="en" legal-region="bc"
	//          ></legal-counter>anim id est laborum<legal-counter
	//            v-overlay-opener="legal-overlay"
	//            legal-key="fibre-promotions-phone"
	//            legal-lang="en" legal-region="bc"
	//            ></legal-counter>.
	//      </p>
	//    </div>
	//  </section>
	//
	//  <overlay-container>
	//   <overlay overlay-key="legal-overlay">
	//     <h4 class="hy_c-headline hy_c-headline--h4" slot="overlay-header">Terms and conditions</h4>
	//     <article slot="overlay-body">
	//         <legal-container></legal-container>
	//     </article>
	//   </overlay>
	// </overlay-container>
	// </template>
	//
	// <script>
	exports.default = {};
	// </script>

	/* generated by vue-loader */

/***/ },

/***/ 16:
/***/ function(module, exports) {

	module.exports = "\n  <section class=\"hy_c-module hy_t-grey\">\n   <div class=\"hy_o-wrapper\">\n     <h2 class=\"hy_c-headline hy_c-headline--h2 hy_t-grey\">Legal System</h2>\n     <hr class=\"hy_u-space-mb-2\">\n     <p class=\"hy_c-copy hy_c-copy--body hy_t-grey\">\n       Lorem ipsum<legal-counter\n         v-overlay-opener=\"legal-overlay\"\n         legal-key=\"hs-referral-terms\"\n         legal-lang=\"en\" legal-region=\"bc\"\n         ></legal-counter> dolor sit amet, consectetur adipiscing elit,\n       sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n       <legal-counter\n         v-overlay-opener=\"legal-overlay\"\n         legal-key=\"1-year-offer-stim\"\n         legal-lang=\"en\" legal-region=\"bc\"\n         ></legal-counter>\n       Ut enim ad<legal-counter\n         v-overlay-opener=\"legal-overlay\"\n         legal-key=\"fibre-promotions-ffg\"\n         legal-lang=\"en\" legal-region=\"bc\"\n         ></legal-counter>  minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu <legal-counter\n         v-overlay-opener=\"legal-overlay\"\n         legal-key=\"fibre-free-installation\"\n         legal-lang=\"en\" legal-region=\"bc\"\n         ></legal-counter>fugiat nulla pariatur.\n       Excepteur<legal-counter\n         v-overlay-opener=\"legal-overlay\"\n         legal-key=\"fibre-promotions-ffg\"\n         legal-lang=\"en\" legal-region=\"bc\"\n         ></legal-counter> sint occaecat cupidatat non proident,\n       sunt in culpa qui officia deserunt mollit <legal-counter\n         v-overlay-opener=\"legal-overlay\"\n         legal-key=\"fibre-telus-and-network-logos\"\n         legal-lang=\"en\" legal-region=\"bc\"\n         ></legal-counter>anim id est laborum<legal-counter\n           v-overlay-opener=\"legal-overlay\"\n           legal-key=\"fibre-promotions-phone\"\n           legal-lang=\"en\" legal-region=\"bc\"\n           ></legal-counter>.\n     </p>\n   </div>\n </section>\n\n <overlay-container>\n  <overlay overlay-key=\"legal-overlay\">\n    <h4 class=\"hy_c-headline hy_c-headline--h4\" slot=\"overlay-header\">Terms and conditions</h4>\n    <article slot=\"overlay-body\">\n        <legal-container></legal-container>\n    </article>\n  </overlay>\n</overlay-container>\n";

/***/ }

});
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9leGFtcGxlLWRldi9zcmMvdmlld3MvbGVnYWwtcGFnZS52dWUiLCJ3ZWJwYWNrOi8vL2xlZ2FsLXBhZ2UudnVlIiwid2VicGFjazovLy8uL2V4YW1wbGUtZGV2L3NyYy92aWV3cy9sZWdhbC1wYWdlLnZ1ZT9hZGViIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7O0FBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxnR0FBK0Y7QUFDL0Y7QUFDQSxhQUFpQixjQUFjO0FBQy9CO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLElBQUc7QUFDSDtBQUNBO0FBQ0EsRUFBQyxJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQkNtQ0Q7Ozs7Ozs7Ozs7QUN6REEsdTFFIiwiZmlsZSI6IjMuYXBwLmpzIiwic291cmNlc0NvbnRlbnQiOlsidmFyIF9fdnVlX3NjcmlwdF9fLCBfX3Z1ZV90ZW1wbGF0ZV9fXG5fX3Z1ZV9zY3JpcHRfXyA9IHJlcXVpcmUoXCIhIWJhYmVsIS4vLi4vLi4vLi4vbm9kZV9tb2R1bGVzL3Z1ZS1sb2FkZXIvbGliL3NlbGVjdG9yLmpzP3R5cGU9c2NyaXB0JmluZGV4PTAhLi9sZWdhbC1wYWdlLnZ1ZVwiKVxuaWYgKF9fdnVlX3NjcmlwdF9fICYmXG4gICAgX192dWVfc2NyaXB0X18uX19lc01vZHVsZSAmJlxuICAgIE9iamVjdC5rZXlzKF9fdnVlX3NjcmlwdF9fKS5sZW5ndGggPiAxKSB7XG4gIGNvbnNvbGUud2FybihcIlt2dWUtbG9hZGVyXSBleGFtcGxlLWRldi9zcmMvdmlld3MvbGVnYWwtcGFnZS52dWU6IG5hbWVkIGV4cG9ydHMgaW4gKi52dWUgZmlsZXMgYXJlIGlnbm9yZWQuXCIpfVxuX192dWVfdGVtcGxhdGVfXyA9IHJlcXVpcmUoXCIhIXZ1ZS1odG1sP3JlbW92ZVJlZHVuZGFudEF0dHJpYnV0ZXM9ZmFsc2UhLi8uLi8uLi8uLi9ub2RlX21vZHVsZXMvdnVlLWxvYWRlci9saWIvc2VsZWN0b3IuanM/dHlwZT10ZW1wbGF0ZSZpbmRleD0wIS4vbGVnYWwtcGFnZS52dWVcIilcbm1vZHVsZS5leHBvcnRzID0gX192dWVfc2NyaXB0X18gfHwge31cbmlmIChtb2R1bGUuZXhwb3J0cy5fX2VzTW9kdWxlKSBtb2R1bGUuZXhwb3J0cyA9IG1vZHVsZS5leHBvcnRzLmRlZmF1bHRcbmlmIChfX3Z1ZV90ZW1wbGF0ZV9fKSB7XG4odHlwZW9mIG1vZHVsZS5leHBvcnRzID09PSBcImZ1bmN0aW9uXCIgPyAobW9kdWxlLmV4cG9ydHMub3B0aW9ucyB8fCAobW9kdWxlLmV4cG9ydHMub3B0aW9ucyA9IHt9KSkgOiBtb2R1bGUuZXhwb3J0cykudGVtcGxhdGUgPSBfX3Z1ZV90ZW1wbGF0ZV9fXG59XG5pZiAobW9kdWxlLmhvdCkgeyhmdW5jdGlvbiAoKSB7ICBtb2R1bGUuaG90LmFjY2VwdCgpXG4gIHZhciBob3RBUEkgPSByZXF1aXJlKFwidnVlLWhvdC1yZWxvYWQtYXBpXCIpXG4gIGhvdEFQSS5pbnN0YWxsKHJlcXVpcmUoXCJ2dWVcIiksIGZhbHNlKVxuICBpZiAoIWhvdEFQSS5jb21wYXRpYmxlKSByZXR1cm5cbiAgdmFyIGlkID0gXCJfdi1hNjJjYTNkYy9sZWdhbC1wYWdlLnZ1ZVwiXG4gIGlmICghbW9kdWxlLmhvdC5kYXRhKSB7XG4gICAgaG90QVBJLmNyZWF0ZVJlY29yZChpZCwgbW9kdWxlLmV4cG9ydHMpXG4gIH0gZWxzZSB7XG4gICAgaG90QVBJLnVwZGF0ZShpZCwgbW9kdWxlLmV4cG9ydHMsIF9fdnVlX3RlbXBsYXRlX18pXG4gIH1cbn0pKCl9XG5cblxuLyoqKioqKioqKioqKioqKioqXG4gKiogV0VCUEFDSyBGT09URVJcbiAqKiAuL2V4YW1wbGUtZGV2L3NyYy92aWV3cy9sZWdhbC1wYWdlLnZ1ZVxuICoqIG1vZHVsZSBpZCA9IDE0XG4gKiogbW9kdWxlIGNodW5rcyA9IDNcbiAqKi8iLCI8dGVtcGxhdGU+XG4gIDxzZWN0aW9uIGNsYXNzPVwiaHlfYy1tb2R1bGUgaHlfdC1ncmV5XCI+XG4gICA8ZGl2IGNsYXNzPVwiaHlfby13cmFwcGVyXCI+XG4gICAgIDxoMiBjbGFzcz1cImh5X2MtaGVhZGxpbmUgaHlfYy1oZWFkbGluZS0taDIgaHlfdC1ncmV5XCI+TGVnYWwgU3lzdGVtPC9oMj5cbiAgICAgPGhyIGNsYXNzPVwiaHlfdS1zcGFjZS1tYi0yXCI+XG4gICAgIDxwIGNsYXNzPVwiaHlfYy1jb3B5IGh5X2MtY29weS0tYm9keSBoeV90LWdyZXlcIj5cbiAgICAgICBMb3JlbSBpcHN1bTxsZWdhbC1jb3VudGVyXG4gICAgICAgICB2LW92ZXJsYXktb3BlbmVyPVwibGVnYWwtb3ZlcmxheVwiXG4gICAgICAgICBsZWdhbC1rZXk9XCJocy1yZWZlcnJhbC10ZXJtc1wiXG4gICAgICAgICBsZWdhbC1sYW5nPVwiZW5cIiBsZWdhbC1yZWdpb249XCJiY1wiXG4gICAgICAgICA+PC9sZWdhbC1jb3VudGVyPiBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LFxuICAgICAgIHNlZCBkbyBlaXVzbW9kIHRlbXBvciBpbmNpZGlkdW50IHV0IGxhYm9yZSBldCBkb2xvcmUgbWFnbmEgYWxpcXVhLlxuICAgICAgIDxsZWdhbC1jb3VudGVyXG4gICAgICAgICB2LW92ZXJsYXktb3BlbmVyPVwibGVnYWwtb3ZlcmxheVwiXG4gICAgICAgICBsZWdhbC1rZXk9XCIxLXllYXItb2ZmZXItc3RpbVwiXG4gICAgICAgICBsZWdhbC1sYW5nPVwiZW5cIiBsZWdhbC1yZWdpb249XCJiY1wiXG4gICAgICAgICA+PC9sZWdhbC1jb3VudGVyPlxuICAgICAgIFV0IGVuaW0gYWQ8bGVnYWwtY291bnRlclxuICAgICAgICAgdi1vdmVybGF5LW9wZW5lcj1cImxlZ2FsLW92ZXJsYXlcIlxuICAgICAgICAgbGVnYWwta2V5PVwiZmlicmUtcHJvbW90aW9ucy1mZmdcIlxuICAgICAgICAgbGVnYWwtbGFuZz1cImVuXCIgbGVnYWwtcmVnaW9uPVwiYmNcIlxuICAgICAgICAgPjwvbGVnYWwtY291bnRlcj4gIG1pbmltIHZlbmlhbSwgcXVpcyBub3N0cnVkIGV4ZXJjaXRhdGlvbiB1bGxhbWNvIGxhYm9yaXMgbmlzaSB1dCBhbGlxdWlwIGV4IGVhIGNvbW1vZG8gY29uc2VxdWF0LlxuICAgICAgIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZXByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZXUgPGxlZ2FsLWNvdW50ZXJcbiAgICAgICAgIHYtb3ZlcmxheS1vcGVuZXI9XCJsZWdhbC1vdmVybGF5XCJcbiAgICAgICAgIGxlZ2FsLWtleT1cImZpYnJlLWZyZWUtaW5zdGFsbGF0aW9uXCJcbiAgICAgICAgIGxlZ2FsLWxhbmc9XCJlblwiIGxlZ2FsLXJlZ2lvbj1cImJjXCJcbiAgICAgICAgID48L2xlZ2FsLWNvdW50ZXI+ZnVnaWF0IG51bGxhIHBhcmlhdHVyLlxuICAgICAgIEV4Y2VwdGV1cjxsZWdhbC1jb3VudGVyXG4gICAgICAgICB2LW92ZXJsYXktb3BlbmVyPVwibGVnYWwtb3ZlcmxheVwiXG4gICAgICAgICBsZWdhbC1rZXk9XCJmaWJyZS1wcm9tb3Rpb25zLWZmZ1wiXG4gICAgICAgICBsZWdhbC1sYW5nPVwiZW5cIiBsZWdhbC1yZWdpb249XCJiY1wiXG4gICAgICAgICA+PC9sZWdhbC1jb3VudGVyPiBzaW50IG9jY2FlY2F0IGN1cGlkYXRhdCBub24gcHJvaWRlbnQsXG4gICAgICAgc3VudCBpbiBjdWxwYSBxdWkgb2ZmaWNpYSBkZXNlcnVudCBtb2xsaXQgPGxlZ2FsLWNvdW50ZXJcbiAgICAgICAgIHYtb3ZlcmxheS1vcGVuZXI9XCJsZWdhbC1vdmVybGF5XCJcbiAgICAgICAgIGxlZ2FsLWtleT1cImZpYnJlLXRlbHVzLWFuZC1uZXR3b3JrLWxvZ29zXCJcbiAgICAgICAgIGxlZ2FsLWxhbmc9XCJlblwiIGxlZ2FsLXJlZ2lvbj1cImJjXCJcbiAgICAgICAgID48L2xlZ2FsLWNvdW50ZXI+YW5pbSBpZCBlc3QgbGFib3J1bTxsZWdhbC1jb3VudGVyXG4gICAgICAgICAgIHYtb3ZlcmxheS1vcGVuZXI9XCJsZWdhbC1vdmVybGF5XCJcbiAgICAgICAgICAgbGVnYWwta2V5PVwiZmlicmUtcHJvbW90aW9ucy1waG9uZVwiXG4gICAgICAgICAgIGxlZ2FsLWxhbmc9XCJlblwiIGxlZ2FsLXJlZ2lvbj1cImJjXCJcbiAgICAgICAgICAgPjwvbGVnYWwtY291bnRlcj4uXG4gICAgIDwvcD5cbiAgIDwvZGl2PlxuIDwvc2VjdGlvbj5cblxuIDxvdmVybGF5LWNvbnRhaW5lcj5cbiAgPG92ZXJsYXkgb3ZlcmxheS1rZXk9XCJsZWdhbC1vdmVybGF5XCI+XG4gICAgPGg0IGNsYXNzPVwiaHlfYy1oZWFkbGluZSBoeV9jLWhlYWRsaW5lLS1oNFwiIHNsb3Q9XCJvdmVybGF5LWhlYWRlclwiPlRlcm1zIGFuZCBjb25kaXRpb25zPC9oND5cbiAgICA8YXJ0aWNsZSBzbG90PVwib3ZlcmxheS1ib2R5XCI+XG4gICAgICAgIDxsZWdhbC1jb250YWluZXI+PC9sZWdhbC1jb250YWluZXI+XG4gICAgPC9hcnRpY2xlPlxuICA8L292ZXJsYXk+XG48L292ZXJsYXktY29udGFpbmVyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbmV4cG9ydCBkZWZhdWx0IHtcbn07XG48L3NjcmlwdD5cblxuXG5cbi8qKiBXRUJQQUNLIEZPT1RFUiAqKlxuICoqIGxlZ2FsLXBhZ2UudnVlPzJjMTgyNTdlXG4gKiovIiwibW9kdWxlLmV4cG9ydHMgPSBcIlxcbiAgPHNlY3Rpb24gY2xhc3M9XFxcImh5X2MtbW9kdWxlIGh5X3QtZ3JleVxcXCI+XFxuICAgPGRpdiBjbGFzcz1cXFwiaHlfby13cmFwcGVyXFxcIj5cXG4gICAgIDxoMiBjbGFzcz1cXFwiaHlfYy1oZWFkbGluZSBoeV9jLWhlYWRsaW5lLS1oMiBoeV90LWdyZXlcXFwiPkxlZ2FsIFN5c3RlbTwvaDI+XFxuICAgICA8aHIgY2xhc3M9XFxcImh5X3Utc3BhY2UtbWItMlxcXCI+XFxuICAgICA8cCBjbGFzcz1cXFwiaHlfYy1jb3B5IGh5X2MtY29weS0tYm9keSBoeV90LWdyZXlcXFwiPlxcbiAgICAgICBMb3JlbSBpcHN1bTxsZWdhbC1jb3VudGVyXFxuICAgICAgICAgdi1vdmVybGF5LW9wZW5lcj1cXFwibGVnYWwtb3ZlcmxheVxcXCJcXG4gICAgICAgICBsZWdhbC1rZXk9XFxcImhzLXJlZmVycmFsLXRlcm1zXFxcIlxcbiAgICAgICAgIGxlZ2FsLWxhbmc9XFxcImVuXFxcIiBsZWdhbC1yZWdpb249XFxcImJjXFxcIlxcbiAgICAgICAgID48L2xlZ2FsLWNvdW50ZXI+IGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQsXFxuICAgICAgIHNlZCBkbyBlaXVzbW9kIHRlbXBvciBpbmNpZGlkdW50IHV0IGxhYm9yZSBldCBkb2xvcmUgbWFnbmEgYWxpcXVhLlxcbiAgICAgICA8bGVnYWwtY291bnRlclxcbiAgICAgICAgIHYtb3ZlcmxheS1vcGVuZXI9XFxcImxlZ2FsLW92ZXJsYXlcXFwiXFxuICAgICAgICAgbGVnYWwta2V5PVxcXCIxLXllYXItb2ZmZXItc3RpbVxcXCJcXG4gICAgICAgICBsZWdhbC1sYW5nPVxcXCJlblxcXCIgbGVnYWwtcmVnaW9uPVxcXCJiY1xcXCJcXG4gICAgICAgICA+PC9sZWdhbC1jb3VudGVyPlxcbiAgICAgICBVdCBlbmltIGFkPGxlZ2FsLWNvdW50ZXJcXG4gICAgICAgICB2LW92ZXJsYXktb3BlbmVyPVxcXCJsZWdhbC1vdmVybGF5XFxcIlxcbiAgICAgICAgIGxlZ2FsLWtleT1cXFwiZmlicmUtcHJvbW90aW9ucy1mZmdcXFwiXFxuICAgICAgICAgbGVnYWwtbGFuZz1cXFwiZW5cXFwiIGxlZ2FsLXJlZ2lvbj1cXFwiYmNcXFwiXFxuICAgICAgICAgPjwvbGVnYWwtY291bnRlcj4gIG1pbmltIHZlbmlhbSwgcXVpcyBub3N0cnVkIGV4ZXJjaXRhdGlvbiB1bGxhbWNvIGxhYm9yaXMgbmlzaSB1dCBhbGlxdWlwIGV4IGVhIGNvbW1vZG8gY29uc2VxdWF0LlxcbiAgICAgICBEdWlzIGF1dGUgaXJ1cmUgZG9sb3IgaW4gcmVwcmVoZW5kZXJpdCBpbiB2b2x1cHRhdGUgdmVsaXQgZXNzZSBjaWxsdW0gZG9sb3JlIGV1IDxsZWdhbC1jb3VudGVyXFxuICAgICAgICAgdi1vdmVybGF5LW9wZW5lcj1cXFwibGVnYWwtb3ZlcmxheVxcXCJcXG4gICAgICAgICBsZWdhbC1rZXk9XFxcImZpYnJlLWZyZWUtaW5zdGFsbGF0aW9uXFxcIlxcbiAgICAgICAgIGxlZ2FsLWxhbmc9XFxcImVuXFxcIiBsZWdhbC1yZWdpb249XFxcImJjXFxcIlxcbiAgICAgICAgID48L2xlZ2FsLWNvdW50ZXI+ZnVnaWF0IG51bGxhIHBhcmlhdHVyLlxcbiAgICAgICBFeGNlcHRldXI8bGVnYWwtY291bnRlclxcbiAgICAgICAgIHYtb3ZlcmxheS1vcGVuZXI9XFxcImxlZ2FsLW92ZXJsYXlcXFwiXFxuICAgICAgICAgbGVnYWwta2V5PVxcXCJmaWJyZS1wcm9tb3Rpb25zLWZmZ1xcXCJcXG4gICAgICAgICBsZWdhbC1sYW5nPVxcXCJlblxcXCIgbGVnYWwtcmVnaW9uPVxcXCJiY1xcXCJcXG4gICAgICAgICA+PC9sZWdhbC1jb3VudGVyPiBzaW50IG9jY2FlY2F0IGN1cGlkYXRhdCBub24gcHJvaWRlbnQsXFxuICAgICAgIHN1bnQgaW4gY3VscGEgcXVpIG9mZmljaWEgZGVzZXJ1bnQgbW9sbGl0IDxsZWdhbC1jb3VudGVyXFxuICAgICAgICAgdi1vdmVybGF5LW9wZW5lcj1cXFwibGVnYWwtb3ZlcmxheVxcXCJcXG4gICAgICAgICBsZWdhbC1rZXk9XFxcImZpYnJlLXRlbHVzLWFuZC1uZXR3b3JrLWxvZ29zXFxcIlxcbiAgICAgICAgIGxlZ2FsLWxhbmc9XFxcImVuXFxcIiBsZWdhbC1yZWdpb249XFxcImJjXFxcIlxcbiAgICAgICAgID48L2xlZ2FsLWNvdW50ZXI+YW5pbSBpZCBlc3QgbGFib3J1bTxsZWdhbC1jb3VudGVyXFxuICAgICAgICAgICB2LW92ZXJsYXktb3BlbmVyPVxcXCJsZWdhbC1vdmVybGF5XFxcIlxcbiAgICAgICAgICAgbGVnYWwta2V5PVxcXCJmaWJyZS1wcm9tb3Rpb25zLXBob25lXFxcIlxcbiAgICAgICAgICAgbGVnYWwtbGFuZz1cXFwiZW5cXFwiIGxlZ2FsLXJlZ2lvbj1cXFwiYmNcXFwiXFxuICAgICAgICAgICA+PC9sZWdhbC1jb3VudGVyPi5cXG4gICAgIDwvcD5cXG4gICA8L2Rpdj5cXG4gPC9zZWN0aW9uPlxcblxcbiA8b3ZlcmxheS1jb250YWluZXI+XFxuICA8b3ZlcmxheSBvdmVybGF5LWtleT1cXFwibGVnYWwtb3ZlcmxheVxcXCI+XFxuICAgIDxoNCBjbGFzcz1cXFwiaHlfYy1oZWFkbGluZSBoeV9jLWhlYWRsaW5lLS1oNFxcXCIgc2xvdD1cXFwib3ZlcmxheS1oZWFkZXJcXFwiPlRlcm1zIGFuZCBjb25kaXRpb25zPC9oND5cXG4gICAgPGFydGljbGUgc2xvdD1cXFwib3ZlcmxheS1ib2R5XFxcIj5cXG4gICAgICAgIDxsZWdhbC1jb250YWluZXI+PC9sZWdhbC1jb250YWluZXI+XFxuICAgIDwvYXJ0aWNsZT5cXG4gIDwvb3ZlcmxheT5cXG48L292ZXJsYXktY29udGFpbmVyPlxcblwiO1xuXG5cbi8qKioqKioqKioqKioqKioqKlxuICoqIFdFQlBBQ0sgRk9PVEVSXG4gKiogLi9+L3Z1ZS1odG1sLWxvYWRlcj9yZW1vdmVSZWR1bmRhbnRBdHRyaWJ1dGVzPWZhbHNlIS4vfi92dWUtbG9hZGVyL2xpYi9zZWxlY3Rvci5qcz90eXBlPXRlbXBsYXRlJmluZGV4PTAhLi9leGFtcGxlLWRldi9zcmMvdmlld3MvbGVnYWwtcGFnZS52dWVcbiAqKiBtb2R1bGUgaWQgPSAxNlxuICoqIG1vZHVsZSBjaHVua3MgPSAzXG4gKiovIl0sInNvdXJjZVJvb3QiOiIifQ==